# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dailyfitapi:
    image: dailyfitapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5182:5182
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ConnectionStrings__DefaultConnection=Server=locahost;Database=filme;User=root;Password=root;
      - ConnectionStrings__DefaultConnection=Server=db;Database=mydb;User=apiuser;Password=apipassword;

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: